import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {buildStyles, CircularProgressbar} from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import React from "react";
import Chart from "chart.js";
import Image from "next/image";
import {ProtectRoute} from "@/services/protectedRoutes";

 function TopPage() {
    React.useEffect(() => {
        var config = {
            type: "line", data: {
                labels: ["6月", "7月", "8月", "9月", "10月", "11月", "12月"], backgroundColor: '#2E2E2E', datasets: [{
                    label: new Date().getFullYear(),
                    backgroundColor: "#3182ce",
                    borderColor: "#3182ce",
                    data: [65, 78, 66, 44, 56, 67, 75],
                    fill: false,
                }, {
                    label: new Date().getFullYear() - 1,
                    fill: false,
                    backgroundColor: "#edf2f7",
                    borderColor: "#edf2f7",
                    data: [40, 68, 86, 74, 56, 60, 87],
                },],
            }, options: {
                maintainAspectRatio: false, responsive: true, title: {
                    display: false, text: "Sales Charts", fontColor: "white",
                }, legend: {
                    labels: {
                        fontColor: "white",
                    }, align: "end", position: "bottom",
                }, tooltips: {
                    mode: "index", intersect: false,
                }, hover: {
                    mode: "nearest", intersect: true,
                }, scales: {
                    xAxes: [{
                        ticks: {
                            fontColor: "#FFFFFF",
                        }, display: true, scaleLabel: {
                            display: true, labelString: "Month", fontColor: "white",
                        }, gridLines: {
                            display: true,
                            borderDash: [2],
                            borderDashOffset: [2],
                            color: "#777777",
                            zeroLineColor: "#777777",
                            zeroLineBorderDash: [2],
                            zeroLineBorderDashOffset: [2],
                        },
                    },], yAxes: [{
                        ticks: {
                            fontColor: "rgba(255,255,255,.7)",
                        }, display: false, scaleLabel: {
                            display: false, labelString: "Value", fontColor: "white",
                        }, gridLines: {
                            borderDash: [3],
                            borderDashOffset: [3],
                            drawBorder: false,
                            color: "rgba(255, 255, 255, 0.15)",
                            zeroLineColor: "rgba(33, 37, 41, 0)",
                            zeroLineBorderDash: [2],
                            zeroLineBorderDashOffset: [2],
                        },
                    },],
                },
            },
        };
        var ctx = document.getElementById("line-chart").getContext("2d");
        window.myLine = new Chart(ctx, config);
    }, []);
    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className={styles.main}>
            <div className={styles.rowCustom}>
                <div className={`col-md-5 ${styles.dateAchievement}`}>
                    <div style={{width: 200, height: 200}} className={styles.circle}>
                        <CircularProgressbar
                            value={75}
                            text={`05/21 ${75}%`}
                            styles={buildStyles({
                                rotation: 0.25,
                                strokeLinecap: 'butt',
                                textSize: '16px',

                                pathTransitionDuration: 0.5,

                                pathColor: `rgba(62, 152, 199, ${75 / 100})`,
                                textColor: '#FFFFFF',
                                trailColor: '#FFFFFF',
                                backgroundColor: 'none',
                            })}
                        />;
                    </div>
                </div>
                <div className="col-md-7">
                    <div
                        className={`relative flex flex-col min-w-0 break-words w-full mb-6 rounded ${styles.chart}`}>
                        <div className="rounded-t mb-0 px-4 py-3 bg-transparent">
                            <div className="flex flex-wrap items-center">

                            </div>
                        </div>
                        <div className="p-4 flex-auto">
                            {/* Chart */}
                            <div className="relative h-350-px">
                                <canvas className={styles.lineChart} id="line-chart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className={`${styles.rowCustom}`}>
                <a className={`${styles.dietDay} ${styles.colDiet}`}>
                    <div className={styles.diet}>
                        <div className={styles.contentDiet}>
                            <Image
                                src="/background/image_diet.png"
                                alt="Vercel Logo"
                                width={100}
                                height={84}
                                priority
                            />
                            <p>Morning</p>
                        </div>
                    </div>
                </a>

                <a className={`${styles.dietDay} ${styles.colDiet}`}>
                    <div className={styles.diet}>
                        <div className={styles.contentDiet}>
                            <Image
                                src="/background/image_diet.png"
                                alt="Vercel Logo"
                                width={100}
                                height={84}
                                priority
                            />
                            <p>Morning</p>
                        </div>
                    </div>
                </a>

                <a className={`${styles.dietDay} ${styles.colDiet}`}>
                    <div className={styles.diet}>
                        <div className={styles.contentDiet}>
                            <Image
                                src="/background/image_diet.png"
                                alt="Vercel Logo"
                                width={100}
                                height={84}
                                priority
                            />
                            <p>Morning</p>
                        </div>
                    </div>
                </a>

                <a className={`${styles.dietDay} ${styles.colDiet}`}>
                    <div className={styles.diet}>
                        <div className={styles.contentDiet}>
                            <Image
                                src="/background/image_diet.png"
                                alt="Vercel Logo"
                                width={100}
                                height={84}
                                priority
                            />
                            <p>Morning</p>
                        </div>
                    </div>
                </a>
            </div>

            {/*detail diet*/}
            <div className={styles.rowCustom} style={{justifyContent: "center"}}>
                <div className={styles.detailDiet}>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                    <a className={styles.foodDate}>
                        <Image src="/foods/morning.png"
                               alt="morning"
                               width={300}
                               height={300}
                               priority/>
                        <div className={styles.foodDateTitle}>
                            <p>05.21 <span>Morning</span></p>
                        </div>
                    </a>
                </div>
            </div>

            <div className={`${styles.rowCustom} ${styles.btnTop}`}>
                <button className={styles.btnTopPage}>
                    記録をもっと見る
                </button>
            </div>
        </main>
    </>)
}
export default ProtectRoute(TopPage);