import Head from 'next/head'
import 'react-circular-progressbar/dist/styles.css';
import React, {useEffect, useState} from "react";
import styles from '@/styles/Landing.module.css'
import Image from "next/image";
import ServiceApi from "@/services/sevice.api";

export default function TopPage() {
    const [news, setNews] = useState([]);
    const [page, setPage] = useState(1);

    async function asyncFetchNews(page = 1) {
        let res = await ServiceApi.get('/new', {'page': page})
        if (typeof res !== 'undefined' && res.return) {
            if (page !== 1) {
                let dataNews = news
                res.result.push(...dataNews)
            }
            setNews(res.result)
            let pagination = res.pagination
            setPage(pagination.current_page)
            if (pagination.current_page === pagination.last_page) {
                document.getElementById('show-more').style.display = 'none'
            }
        }
    }

    async function loadMore() {
        let currentPage = page
        await asyncFetchNews(++currentPage)
    }

    useEffect(() => {
        asyncFetchNews()
    }, []);
    return (<>
        <Head>
            <title>Langding Page</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className={styles.main}>
            <div className={`${styles.rowCustom}`}>
                <a className={`${styles.dietDay} ${styles.colDiet}`} href="#">
                    <div className={styles.diet}>
                        <h5>RECOMMENDED COLUMN</h5>
                        <hr width="50%" align="center"/>
                        <p>美容</p>
                    </div>
                </a>
                <a className={`${styles.dietDay} ${styles.colDiet}`} href="#">
                    <div className={styles.diet}>
                        <h5>RECOMMENDED DIET</h5>
                        <hr width="50%" align="center"/>
                        <p>ダイエット</p>
                    </div>
                </a>
                <a className={`${styles.dietDay} ${styles.colDiet}`} href="#">
                    <div className={styles.diet}>
                        <h5>RECOMMENDED BEAUTY</h5>
                        <hr width="50%" align="center"/>
                        <p>美容</p>
                    </div>
                </a>
                <a className={`${styles.dietDay} ${styles.colDiet}`} href="#">
                    <div className={styles.diet}>
                        <h5>RECOMMENDED HEALTH</h5>
                        <hr width="50%" align="center"/>
                        <p>健康</p>
                    </div>
                </a>
            </div>

            <div className={`${styles.rowCustom} ${styles.news}`}>
                {news.map((newData, index) => (
                    <div className={styles.detailDiet} key={index}>
                        <div className={styles.foodDate}>
                            <a href="#">
                                <Image src={newData.image}
                                       alt={newData.title}
                                       width={300}
                                       height={185.21}
                                       priority/>
                                <div className={styles.foodDateTitle}>
                                    <p>{newData.date}</p>
                                </div>
                                <p className={styles.titleNews}>{newData.title}</p>
                                { typeof newData.tags !== 'undefined' && newData.tags.length !== 0 ?
                                <p className={styles.tag}>
                                    {
                                        newData.tags.map((tag, i) => (
                                            <span key={`$span_${i}`}>{tag.name} </span>
                                        ))}
                                </p>
                                    : <p></p> }
                            </a>
                        </div>
                    </div>))}

            </div>

            <div className={`${styles.rowCustom} ${styles.btnTop}`} id="show-more" onClick={loadMore}>
                <button className={styles.landingPage}>
                    記録をもっと見る
                </button>
            </div>
        </main>
    </>)
}