import Head from 'next/head'
import React, {FormEvent} from "react";
import useAuth from "@/services/context.js";
import {redirectServerSide} from "@/services/cookies";
export default function Login() {
    const { login } = useAuth();

    async function onSubmit(event) {
        event.preventDefault()
        login( event.target.email.value, event.target.password.value)
    }

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="container">
            <div className="vh-100 d-flex justify-content-center align-items-center">
                <div className="col-md-4 p-5 shadow-sm border rounded-3">
                    <h2 className="text-center mb-4 text-primary">Login Form </h2>
                    <form onSubmit={onSubmit} >
                        <div className="mb-3">
                            <label htmlFor="exampleInputEmail1" className="form-label">Username : </label>
                            <input type="email" className="form-control border border-primary"
                                   aria-describedby="emailHelp"
                                   name="email"
                                   required/>
                            <span className="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                        <div className="mb-3">
                            <label htmlFor="exampleInputPassword1" className="form-label">Password : </label>
                            <input type="password" name="password" className="form-control border border-primary" />
                            <span className="invalid-feedback" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                        <div className="d-grid">
                            <button className="btn btn-primary" type="submit">Login</button>
                        </div>
                    </form>
                    <div className="mt-3">
                    </div>
                </div>
            </div>
        </main>
    </>)
}

export const getServerSideProps = async (context) => {
    redirectServerSide(context);
    return {
        props: {},
    };
};
